### ISSUE TITLE
青龙面板京喜签到出错

### ISSUE THREAD

**Issue by lyiangsh** [chinnkarahoi/jd_scripts#5]
❗️京喜签到, 错误!
TypeError: data.data.tasks is not iterable
    at /ql/scripts/chinnkarahoi_jx_sign.js:121:38
    at isSurge.isLoon.isQuanX.isNode.got.on.then.message (/ql/scripts/chinnkarahoi_jx_sign.js:315:4869)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
任务完成失败，错误信息not sign
请教

**Comment by githubwyj** [comment]
我查了一下，发现那个“getTaskList”请求返回结果如下
`{"data":{},"errMsg":"success","retCode":0}`
加一下判断
![image](https://user-images.githubusercontent.com/24646311/120260212-0353bf80-c2c8-11eb-9a6a-fd06cd3db166.png)

不过还是等大佬抓一下接口
我电脑的fiddler一直抓不到。。。尴尬

**Comment by hdstar2009** [comment]
青龙面板的问题不是应该发到青龙项目地方去吗
